import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { fetchMessages, sendChatMessage, createConversation } from '../lib/api';
import { Message, Conversation } from '../types/chat';
import {
  Send,
  Plus,
  Bot,
  User as UserIcon,
  Sparkles,
  Loader2,
  AlertCircle,
  Copy,
  Check,
} from 'lucide-react';

export const ChatPage: React.FC = () => {
  const { id: routeConvId } = useParams<{ id?: string }>();
  const navigate = useNavigate();
  const { user } = useAuth();

  const [conversationId, setConversationId] = useState<string | undefined>(routeConvId);
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputMessage, setInputMessage] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [isFetchingHistory, setIsFetchingHistory] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  // Sync conversation ID from route params
  useEffect(() => {
    setConversationId(routeConvId);
    if (routeConvId) {
      loadHistory(routeConvId);
    } else {
      setMessages([]);
    }
  }, [routeConvId]);

  const loadHistory = async (convId: string) => {
    setIsFetchingHistory(true);
    setError(null);
    try {
      const msgs = await fetchMessages(convId);
      setMessages(msgs);
    } catch (err: any) {
      setError('Failed to load message history.');
    } finally {
      setIsFetchingHistory(false);
    }
  };

  // Scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  const handleStartNewChat = async () => {
    setError(null);
    setMessages([]);
    setConversationId(undefined);
    navigate('/chat');
    setTimeout(() => {
      inputRef.current?.focus();
    }, 100);
  };

  const handleSendMessage = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    const trimmed = inputMessage.trim();
    if (!trimmed || isLoading) return;

    setError(null);
    setInputMessage('');

    // Optimistic user message bubble
    const tempUserMsg: Message = {
      id: 'temp-user-' + Date.now(),
      role: 'user',
      content: trimmed,
      created_at: new Date().toISOString(),
    };

    setMessages((prev) => [...prev, tempUserMsg]);
    setIsLoading(true);

    try {
      const res = await sendChatMessage(trimmed, conversationId);

      // If new conversation was generated by backend, update state and route
      if (!conversationId && res.conversationId) {
        setConversationId(res.conversationId);
        navigate(`/chat/${res.conversationId}`, { replace: true });
      }

      // Replace optimistic message and append real AI message
      setMessages((prev) => {
        const filtered = prev.filter((m) => m.id !== tempUserMsg.id);
        return [...filtered, res.userMessage, res.aiResponse];
      });
    } catch (err: any) {
      console.error('Chat error:', err);
      setError(err?.message || 'Failed to generate AI response. Please check your backend connection.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const handleCopyCode = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="flex-1 flex flex-col h-full overflow-hidden bg-[#090d16] relative">
      {/* Full Page Chat Header Bar */}
      <div className="h-16 px-6 border-b border-slate-800/80 bg-[#0d1322]/80 backdrop-blur-md flex items-center justify-between flex-shrink-0 z-20">
        <div className="flex items-center space-x-3">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-indigo-600 to-purple-600 p-0.5 flex items-center justify-center shadow-lg shadow-indigo-500/20">
            <div className="w-full h-full bg-[#0d1322] rounded-[10px] flex items-center justify-center">
              <Bot className="w-5 h-5 text-indigo-400" />
            </div>
          </div>
          <div>
            <h2 className="text-sm font-bold text-white flex items-center gap-2">
              AskFlow Assistant
              <span className="w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            </h2>
            <p className="text-[11px] text-slate-400">Powered by Google Gemini 2.5 Flash (@google/genai)</p>
          </div>
        </div>

        {/* New Chat Button */}
        <button
          onClick={handleStartNewChat}
          className="py-2 px-3.5 rounded-xl bg-indigo-600/20 hover:bg-indigo-600/30 text-indigo-300 border border-indigo-500/30 font-medium text-xs flex items-center space-x-1.5 transition-all duration-200"
        >
          <Plus className="w-4 h-4" />
          <span>New Chat</span>
        </button>
      </div>

      {/* Main Message Stream Container (Full Available Area) */}
      <div className="flex-1 overflow-y-auto p-4 md:p-6 space-y-6 max-w-4xl mx-auto w-full">
        {isFetchingHistory ? (
          <div className="h-full flex flex-col items-center justify-center space-y-3 py-20 text-slate-400">
            <Loader2 className="w-8 h-8 text-indigo-500 animate-spin" />
            <p className="text-xs">Loading conversation history...</p>
          </div>
        ) : messages.length === 0 ? (
          /* Empty / Welcome Hero State */
          <div className="h-full flex flex-col items-center justify-center text-center py-16 px-4 space-y-6 max-w-lg mx-auto">
            <div className="w-16 h-16 rounded-2xl bg-gradient-to-tr from-indigo-600 to-purple-600 p-0.5 shadow-2xl shadow-indigo-500/30 flex items-center justify-center animate-glow-pulse">
              <div className="w-full h-full bg-[#0d1322] rounded-[14px] flex items-center justify-center">
                <Sparkles className="w-8 h-8 text-indigo-400" />
              </div>
            </div>
            <div className="space-y-2">
              <h3 className="text-2xl font-bold text-white">How can AskFlow AI assist you today?</h3>
              <p className="text-xs text-slate-400 leading-relaxed">
                Ask questions, generate ideas, analyze code snippets, or draft documents with high-speed intelligence.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 w-full text-left pt-2">
              {[
                'Explain React Hooks in TypeScript',
                'Write an Express.js router with Zod validation',
                'How does Supabase RLS security work?',
                'Design a responsive Tailwind CSS hero component',
              ].map((prompt, idx) => (
                <button
                  key={idx}
                  onClick={() => {
                    setInputMessage(prompt);
                    inputRef.current?.focus();
                  }}
                  className="p-3 rounded-xl glass-card hover:bg-indigo-600/10 hover:border-indigo-500/30 text-xs text-slate-300 hover:text-white transition-all text-left"
                >
                  "{prompt}"
                </button>
              ))}
            </div>
          </div>
        ) : (
          /* Render Message History Bubbles */
          messages.map((msg) => {
            const isUser = msg.role === 'user';
            return (
              <div
                key={msg.id}
                className={`flex items-start space-x-3.5 ${
                  isUser ? 'flex-row-reverse space-x-reverse' : ''
                } animate-fade-in`}
              >
                {/* Avatar Icon */}
                <div
                  className={`w-9 h-9 rounded-xl p-0.5 flex-shrink-0 flex items-center justify-center shadow-md ${
                    isUser
                      ? 'bg-gradient-to-br from-indigo-500 to-purple-600'
                      : 'bg-gradient-to-tr from-indigo-600 via-indigo-500 to-purple-500'
                  }`}
                >
                  <div className="w-full h-full bg-[#0d1322] rounded-[10px] flex items-center justify-center">
                    {isUser ? (
                      <UserIcon className="w-4 h-4 text-indigo-300" />
                    ) : (
                      <Bot className="w-4 h-4 text-purple-300" />
                    )}
                  </div>
                </div>

                {/* Message Bubble Content */}
                <div
                  className={`group relative max-w-[85%] md:max-w-[78%] rounded-2xl p-4 text-sm leading-relaxed ${
                    isUser
                      ? 'bg-indigo-600 text-white rounded-tr-none shadow-lg shadow-indigo-600/20'
                      : 'glass-card bg-[#111726]/90 border-slate-800 text-slate-100 rounded-tl-none shadow-md'
                  }`}
                >
                  {/* Copy Button for Assistant Messages */}
                  {!isUser && (
                    <button
                      onClick={() => handleCopyCode(msg.content, msg.id)}
                      title="Copy Response"
                      className="absolute top-2.5 right-2.5 opacity-0 group-hover:opacity-100 p-1 text-slate-400 hover:text-white bg-slate-800/80 rounded transition"
                    >
                      {copiedId === msg.id ? (
                        <Check className="w-3.5 h-3.5 text-emerald-400" />
                      ) : (
                        <Copy className="w-3.5 h-3.5" />
                      )}
                    </button>
                  )}

                  {/* Render content formatted */}
                  <div className="whitespace-pre-wrap break-words font-sans">
                    {msg.content}
                  </div>

                  <div
                    className={`text-[10px] mt-2 ${
                      isUser ? 'text-indigo-200/70 text-right' : 'text-slate-500'
                    }`}
                  >
                    {new Date(msg.created_at || Date.now()).toLocaleTimeString([], {
                      hour: '2-digit',
                      minute: '2-digit',
                    })}
                  </div>
                </div>
              </div>
            );
          })
        )}

        {/* Loading Indicator Dots */}
        {isLoading && (
          <div className="flex items-start space-x-3.5 animate-fade-in">
            <div className="w-9 h-9 rounded-xl p-0.5 flex-shrink-0 bg-gradient-to-tr from-indigo-600 to-purple-600 shadow-md">
              <div className="w-full h-full bg-[#0d1322] rounded-[10px] flex items-center justify-center">
                <Bot className="w-4 h-4 text-purple-300" />
              </div>
            </div>
            <div className="glass-card bg-[#111726] border-slate-800 p-4 rounded-2xl rounded-tl-none flex items-center space-x-2">
              <span className="text-xs text-slate-400 font-medium">AskFlow is thinking</span>
              <div className="flex items-center space-x-1 pl-1">
                <div className="typing-dot" />
                <div className="typing-dot" />
                <div className="typing-dot" />
              </div>
            </div>
          </div>
        )}

        {/* Error Alert */}
        {error && (
          <div className="p-4 rounded-xl bg-red-500/10 border border-red-500/20 text-red-300 text-xs flex items-center space-x-2">
            <AlertCircle className="w-4 h-4 text-red-400 flex-shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Sticky Bottom Message Input Bar */}
      <div className="p-4 md:p-6 border-t border-slate-800/80 bg-[#0d1322]/90 backdrop-blur-xl flex-shrink-0 z-20">
        <form onSubmit={handleSendMessage} className="max-w-4xl mx-auto relative flex items-end gap-2">
          <div className="relative flex-1">
            <textarea
              ref={inputRef}
              rows={1}
              value={inputMessage}
              onChange={(e) => setInputMessage(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Ask anything... (Press Enter to send, Shift+Enter for newline)"
              disabled={isLoading}
              className="w-full pl-4 pr-12 py-3.5 rounded-2xl glass-input text-white text-sm placeholder-slate-500 focus:outline-none resize-none max-h-32 transition duration-200"
            />
          </div>

          <button
            type="submit"
            disabled={!inputMessage.trim() || isLoading}
            className="h-[46px] w-[46px] rounded-2xl bg-gradient-to-tr from-indigo-600 via-indigo-500 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white flex items-center justify-center shadow-lg shadow-indigo-600/30 transition-all duration-200 disabled:opacity-40 disabled:pointer-events-none active:scale-95 flex-shrink-0"
          >
            {isLoading ? (
              <Loader2 className="w-5 h-5 animate-spin" />
            ) : (
              <Send className="w-5 h-5" />
            )}
          </button>
        </form>
      </div>
    </div>
  );
};
